version: "3.8"

services:
  releasi:
    build: .
    container_name: releasi
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config/settings.yaml:/app/config/settings.yaml:ro
    ports:
      - "8000:8000"
      - "6080:6080"
    environment:
      - RELEASI_LOG_LEVEL=INFO
      - TZ=Europe/Berlin
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: "1.5"
