"""Initial schema: accounts, campaigns, leads, action_log, daily_stats

Revision ID: cff59c2df61b
Revises: 
Create Date: 2026-02-21 16:13:21.037301
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'cff59c2df61b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('li_at_cookie', sa.Text(), nullable=False),
    sa.Column('li_a_cookie', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'SUSPENDED', 'COOKIE_EXPIRED', name='accountstatus'), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('weekly_limit', sa.Integer(), nullable=False),
    sa.Column('warmup_enabled', sa.Boolean(), nullable=False),
    sa.Column('warmup_start_date', sa.Date(), nullable=True),
    sa.Column('warmup_week', sa.Integer(), nullable=False),
    sa.Column('paused_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', name='campaignstatus'), nullable=False),
    sa.Column('connection_message_template', sa.Text(), nullable=True),
    sa.Column('followup_message_template', sa.Text(), nullable=True),
    sa.Column('followup_delay_hours', sa.Integer(), nullable=False),
    sa.Column('csv_filename', sa.String(length=255), nullable=True),
    sa.Column('total_leads', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_account_id'), 'campaigns', ['account_id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('connection_requests_sent', sa.Integer(), nullable=False),
    sa.Column('followup_messages_sent', sa.Integer(), nullable=False),
    sa.Column('connections_accepted', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_daily_stat_account_date')
    )
    op.create_index(op.f('ix_daily_stats_account_id'), 'daily_stats', ['account_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('linkedin_url', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'CONNECTION_REQUESTED', 'CONNECTED', 'FOLLOWUP_SCHEDULED', 'FOLLOWUP_SENT', 'COMPLETED', 'SKIPPED', 'ERROR', 'LIMIT_PAUSED', name='leadstatus'), nullable=False),
    sa.Column('connection_requested_at', sa.DateTime(), nullable=True),
    sa.Column('connection_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('followup_sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'linkedin_url', name='uq_lead_campaign_url')
    )
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index('ix_leads_campaign_status', 'leads', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_leads_scheduled_at', 'leads', ['scheduled_at'], unique=False)
    op.create_table('action_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.Enum('CONNECTION_REQUEST', 'FOLLOWUP_MESSAGE', 'CHECK_ACCEPTANCE', 'LIMIT_DETECTED', 'COOLDOWN_STARTED', 'COOLDOWN_ENDED', 'ERROR', name='actiontype'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'SKIPPED', name='actionlogstatus'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_log_account_id'), 'action_log', ['account_id'], unique=False)
    op.create_index('ix_actionlog_account_type_created', 'action_log', ['account_id', 'action_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_actionlog_account_type_created', table_name='action_log')
    op.drop_index(op.f('ix_action_log_account_id'), table_name='action_log')
    op.drop_table('action_log')
    op.drop_index('ix_leads_scheduled_at', table_name='leads')
    op.drop_index('ix_leads_campaign_status', table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_daily_stats_account_id'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_campaigns_account_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('accounts')
    # ### end Alembic commands ###
